void shuffleArray(int array[], int arrayLength);
void initializeArray(int array[], int arrayLength, int minimum, int maximum);
void quickSort(int arr[], int low, int high, int length);
void selectionSort(int arr[], int n);
void bubbleSort(int arr[], int n);
void insertionSort(int arr[], int n);
void heapSort(int arr[], int N);
void shellSort(int arr[], int n);
void radixSort(int arr[], int n);
void shellSort(int arr[], int n);
void combSort(int arr[], int n);
void CocktailSort(int arr[], int n);
void cycleSort(int arr[], int n);
void oddEvenSort(int arr[], int n);
void gnomeSort(int arr[], int n);
